name: Test

on:
  push:
    branches: [ "main" ]
  # Disable pull_request
  # pull_request:
  #   branches: [ "main" ]

env:
  BUILD_PATH: ${{ github.workspace}}/build
  BASE_TAG: latest
  # Enable if handle merge request 
  # BASE_TAG: ${{ github.run_id }}

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_PATH}}

    - name: Build
      run: cmake --build ${{env.BUILD_PATH}}
